all:
  children:
    # --- LINUX SERVERS ---
    linux_servers: 
      hosts:
        test:
          ansible_host: 10.100.100.10
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/proxmox_key
    ansible_become: true