name: docker
description: Linux with Docker

network:
  inbound_ports:
    - port: 22
      protocol: tcp

    - port: 5432
      protocol: tcp

    - port: 8080
      protocol: tcp

    - port: 9187
      protocol: tcp
      
ansible:
  shared_roles:
    - bootstrap
  service_roles:
    - docker-install